In [1]:
# Activity prediction
# Based on: https://beckernick.github.io/activity-prediction/
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df_features = pd.read_csv('features.txt',header=None)

In [3]:
df_activity_labels = pd.read_csv('activity_labels.txt', sep='\s+',header=None)

In [4]:
X_train = pd.read_csv('X_train.txt',delim_whitespace=True,header=None)

In [5]:
y_train = pd.read_csv('y_train.txt',delim_whitespace=True,header=None)

In [6]:
X_test = pd.read_csv('X_test.txt',delim_whitespace=True,header=None)

In [7]:
y_test = pd.read_csv('y_test.txt',delim_whitespace=True,header=None)

In [8]:
from sklearn.svm import LinearSVC

In [9]:
clf_svc = LinearSVC(random_state = 12, C=0.1, max_iter=5000)

In [10]:
clf_svc.fit(X_train, y_train.values.flatten())

LinearSVC(C=0.1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=5000,
     multi_class='ovr', penalty='l2', random_state=12, tol=0.0001,
     verbose=0)

In [11]:
clf_svc.score(X_test, y_test)

0.9471853257432005

In [14]:
crosstab = pd.crosstab(y_test.values.flatten(), clf_svc.predict(X_test),
                          rownames=['True'], colnames=['Predicted'],
                          margins=True)
crosstab

Predicted    1    2    3    4    5    6   7   8   9  10  11  12   All
True
1          496    0    0    0    0    0   0   0   0   0   0   0   496
2           29  442    0    0    0    0   0   0   0   0   0   0   471
3            4    8  408    0    0    0   0   0   0   0   0   0   420
4            0    4    0  448   55    0   0   0   0   0   1   0   508
5            2    0    0   14  539    0   1   0   0   0   0   0   556
6            0    0    0    0    0  545   0   0   0   0   0   0   545
7            0    1    0    2    2    0  16   1   0   0   1   0    23
8            0    0    0    0    0    0   0  10   0   0   0   0    10
9            0    0    0    0    0    0   0   0  23   0   7   2    32
10           0    0    0    0    0    0   0   0   0  20   0   5    25
11           2    2    0    2    0    1   0   0  10   0  32   0    49
12           0    0    0    0    0    0   0   0   0   7   4  16    27
All        533  457  408  466  596  546  17  11  33  27  45  23  3162

In [15]:
# Remove last column and row
crosstab_clean = crosstab.iloc[:-1, :-1]
crosstab_clean.columns = df_activity_labels.values
crosstab_clean.index = df_activity_labels.values
crosstab_clean

,"(1, WALKING)","(2, WALKING_UPSTAIRS)","(3, WALKING_DOWNSTAIRS)","(4, SITTING)","(5, STANDING)","(6, LAYING)","(7, STAND_TO_SIT)","(8, SIT_TO_STAND)","(9, SIT_TO_LIE)","(10, LIE_TO_SIT)","(11, STAND_TO_LIE)","(12, LIE_TO_STAND)"
"(1, WALKING)",496,0,0,0,0,0,0,0,0,0,0,0
"(2, WALKING_UPSTAIRS)",29,442,0,0,0,0,0,0,0,0,0,0
"(3, WALKING_DOWNSTAIRS)",4,8,408,0,0,0,0,0,0,0,0,0
"(4, SITTING)",0,4,0,448,55,0,0,0,0,0,1,0
"(5, STANDING)",2,0,0,14,539,0,1,0,0,0,0,0
"(6, LAYING)",0,0,0,0,0,545,0,0,0,0,0,0
"(7, STAND_TO_SIT)",0,1,0,2,2,0,16,1,0,0,1,0
"(8, SIT_TO_STAND)",0,0,0,0,0,0,0,10,0,0,0,0
"(9, SIT_TO_LIE)",0,0,0,0,0,0,0,0,23,0,7,2
"(10, LIE_TO_SIT)",0,0,0,0,0,0,0,0,0,20,0,5
"(11, STAND_TO_LIE)",2,2,0,2,0,1,0,0,10,0,32,0
"(12, LIE_TO_STAND)",0,0,0,0,0,0,0,0,0,7,4,16